// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMR4MoZG9bu2O4LVYijv7AAYG8duJRF3o',
    appId: '1:676881753252:web:622c30f77583793dbb7231',
    messagingSenderId: '676881753252',
    projectId: 'pushmkiii',
    authDomain: 'pushmkiii.firebaseapp.com',
    storageBucket: 'pushmkiii.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKGePZRYZw3O6PVLJ15GfsXflnVXet-HI',
    appId: '1:676881753252:android:69029416c89b5101bb7231',
    messagingSenderId: '676881753252',
    projectId: 'pushmkiii',
    storageBucket: 'pushmkiii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4tYFjOuquOiGlNnrSwVicFHVyr2hNIs',
    appId: '1:676881753252:ios:154f1d9468c13c98bb7231',
    messagingSenderId: '676881753252',
    projectId: 'pushmkiii',
    storageBucket: 'pushmkiii.firebasestorage.app',
    iosBundleId: 'br.dev.yago.climappCc20262',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4tYFjOuquOiGlNnrSwVicFHVyr2hNIs',
    appId: '1:676881753252:ios:154f1d9468c13c98bb7231',
    messagingSenderId: '676881753252',
    projectId: 'pushmkiii',
    storageBucket: 'pushmkiii.firebasestorage.app',
    iosBundleId: 'br.dev.yago.climappCc20262',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMR4MoZG9bu2O4LVYijv7AAYG8duJRF3o',
    appId: '1:676881753252:web:28c8bede53848226bb7231',
    messagingSenderId: '676881753252',
    projectId: 'pushmkiii',
    authDomain: 'pushmkiii.firebaseapp.com',
    storageBucket: 'pushmkiii.firebasestorage.app',
  );
}
